name: Main pipeline
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Build/Push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/tools/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/battle-tools:latest
          push: true
